### ISSUE TITLE
Possible to change tag name?

### ISSUE THREAD

**Issue by jerry1970** [Chris--A/ParsedownFilter#1]
Nice extension, could be what I am looking for.

My main problem is that for our website we need some custom codes. An article can have an artist name and titles in it. I taught the authors to use _..._ for titles and *...* for artists. MD converts both to `<em>` tags.

Using ParsedownFilter, could I intercept the `<em>` and see whether it originates from *...* or _..._, and can I then change the `<em>` for artists to `<em class="artist">` and for titles to `<em class="title">`?

I've tried looking for an extension that would accept classes in the form of `{.artist}` to *...* but I can't find anything like that.

Thanks!

**Comment by Chris--A** [comment]
Hi, I'm sure what you want can be done. However in your post, all I see for the author and artist names are `...`.

> I taught the authors to use ... for titles and ... for artists.

Are you wrapping your text in a single asterisk `*` for one option, and a single underline `_` for the other? This would render both in italics (`<em>`).

At a guess there might be a few ways that this could be accomplished (library side, or callback side). I'll have another dig through Parsedown and try a few things.

I like this idea though. I think the easiest way would be trying to record the md initiator for each tag. I have also wanted to add a feature to replace what html tags are output for each md input.

**Comment by jerry1970** [comment]
Ah, sorry for the confusion but yes, you guessed right, we are using asterisk-artist-asterisk and underscore-title-underscore. And yes, those would both render to `<em>`.

Not exactly sure what you mean by library-side and callback-side. I took a good look at Parsedown and Parsedown Extra and think see one way to do it. I will have to split the patterns for EM (now an array with asterisk and underscore) and in the inlineEm function add an extra IF statement that returns either EM for underscores and B for artists.

I could even add an extra class for artists there so later some jQuery function will turn class=artist into a link to the search page.

I still love the idea of being able to add custom classes using `{.myclass}` to inline elements like it already works for several block elements, or even add custom attributes in the form of `{myattr="myvalue"}`.

Back to your comment. I guess what you mean by 'record the md initiator' is that the receiving function gets the original md trigger as well so it knows the difference between asterisk and underscore? That would be amazing, it would give extensions a lot more control.

Doesn't overwriting the html tag in the function do the trick? I should test that...

**Comment by jerry1970** [comment]
I found what I was looking for. I extended ParsedownExtra and made an override of a single method that only adds a single IF statement to the overridden method:

```php
    protected function inlineEmphasis($Excerpt)
    {
        if ( ! isset($Excerpt['text'][1])) {
            return;
        }

        $marker = $Excerpt['text'][0];

        $attributes = [];

        if ($Excerpt['text'][1] === $marker and preg_match($this->StrongRegex[$marker], $Excerpt['text'], $matches)) {
            $emphasis = 'strong';
        } elseif (preg_match($this->EmRegex[$marker], $Excerpt['text'], $matches)) {
            if ($marker == '*') {
                // this is the extension: *...* is an artist
                $emphasis = 'b';
                // adding attributes already works:
                $attributes = ['class' => 'artist'];
            } else {
                // this is the regular flow
                $emphasis = 'em';
            }
        } else {
            return;
        }

        return array(
            'extent' => strlen($matches[0]),
            'element' => array(
                'name' => $emphasis,
                'handler' => 'line',
                'text' => $matches[1],
                'attributes' => $attributes,
            ),
        );
    }
```
Best thing I found out is that the MD target is already known as `$marker`.

Maybe this gives you some info for your own idea?

**Comment by Chris--A** [comment]
Nice, cheers. 

This will definitely be of use. I will look at adding it in a way that allows generic customization of what is searched and replaced. This would allow a very customized filter as there will be effectively a pre & post filtering stage.

**Comment by jerry1970** [comment]
So I don't actually need ParsedownFilter right now, but will keep watching it because we have plans for more curstom tags / classes / attributes.
